export const OTHER_ARCHETYPE = "Other / Emerging";

const CURRENT_LIMITLESS_2026_ARCHETYPES = [
  "Dragapult",
  "Dragapult Dusknoir",
  "Mega Greninja",
  "Slowking",
  "N's Zoroark",
  "Crustle",
  "Alakazam Dudunsparce",
  "Ogerpon Meganium Hydrapple",
  "Hydrapple",
  "Ogerpon Box",
  "Beedrill",
  "Lillie's Clefairy",
  "Lucario Hariyama",
  "Rocket's Honchkrow",
  "Mega Lucario",
  "Rocket's Mewtwo",
  "Dragapult Blaziken",
  "Festival Lead",
  "Raging Bolt",
  "Alakazam",
  "Hop's Trevenant",
  "Ethan's Typhlosion",
  "Cynthia's Garchomp",
  "Marnie's Grimmsnarl",
  "Metagross",
  "Mega Lopunny",
  "Mega Starmie",
  "Ogerpon Meganium",
  "Archaludon",
  OTHER_ARCHETYPE,
] as const;

const LEGACY_POST_ROTATION_2026_ARCHETYPES = [
  "Dragapult ex",
  "Mega Greninja",
  "Ogerpon Meganium",
  "Mega Lucario",
  "Mega Starmie",
  "Beedrill",
  "Slowking",
  "Mega Lopunny",
  "N's Zoroark",
  "Raging Bolt",
  "Rocket's Mewtwo",
  "Alakazam",
  "Rocket's Honchkrow",
  "Cynthia's Garchomp",
  "Festival Lead",
  "Marnie's Grimmsnarl",
  "Greninja",
  "Crustle",
  "Basic Box",
  "Ceruledge",
  "Archaludon",
  "Okidogi",
  "Hop's Trevenant",
  "Ethan's Typhlosion",
  "Mega Froslass",
  "Metagross",
  "Bloodmoon Ursaluna",
  "Mega Venusaur",
  "Hydreigon",
  "Hop's Zacian",
  "Mega Charizard X",
  "Steven's Metagross",
  "Mega Diancie",
  "Lillie's Clefairy",
  "Kangaskhan Bouffalant",
  "Mega Zygarde",
  "Flareon",
  "Yanmega",
  "Doublade",
  "Decidueye",
  "Mega Dragonite",
  "Mega Manectric",
  "Bronzong",
  "Froslass Munkidori",
  "Mega Sharpedo",
  "Toxtricity",
  "Joltik Box",
  "Mega Absol Box",
  "Tera Box",
  "Rocket's Spidops",
  "Paldean Tauros",
  "Mega Feraligatr",
  "Mega Gengar",
  "Iono's Bellibolt",
  "Hydrapple",
  "Blaziken",
  "Palafin",
  "Eelektrik",
  "Dudunsparce Control",
  "Mamoswine",
  "Azumarill",
  "Heatran Metang",
  "Jellicent Dusknoir",
  "Ethan's Magcargo",
  "Slaking",
  "Galvantula",
  "Milotic",
  "Ogerpon",
  "Misty's Gyarados",
  "Cinderace",
  "Dragapult Blaziken",
  "Alakazam Dudunsparce",
  "Dragapult Dusknoir",
  "Starmie Froslass",
  "Raging Bolt Ogerpon",
  "Okidogi Barbaracle",
  "Grimmsnarl Froslass",
  "Mega Lucario ex",
  "Dragapult Dudunsparce",
  "Ogerpon Box",
  "Flareon Noctowl",
  "Starmie Dusknoir",
  "Diancie Dusknoir",
  "Lopunny Dudunsparce",
  "Ursaluna Lunatone",
  "Hydrapple Ogerpon",
  "Toxtricity Box",
  "Sharpedo Toxtricity",
  "Zygarde Barbaracle",
  "Mega Abomasnow",
  "Archaludon Zoroark",
  "Mega Zygarde ex",
] as const;

export const POST_ROTATION_2026_ARCHETYPES = [
  ...CURRENT_LIMITLESS_2026_ARCHETYPES,
  ...LEGACY_POST_ROTATION_2026_ARCHETYPES,
] as const;

export const PRE_ROTATION_2025_2026_ARCHETYPES = [
  "Charizard ex",
  "Gardevoir ex",
  "Gholdengo ex",
  "Dragapult ex",
  "Raging Bolt Ogerpon",
  "Miraidon ex",
  "Roaring Moon ex",
  "Lost Zone Box",
  "Chien-Pao ex",
  "Ancient Box",
  "Future Box",
  "Lugia VSTAR",
  "Other / Emerging",
] as const;

export function getArchetypeOptions(
  _format: string | null | undefined,
  existingArchetypes: (string | null)[] = []
) {
  const existing = existingArchetypes.filter(
    (archetype): archetype is string => Boolean(archetype)
  );

  return Array.from(new Set([...POST_ROTATION_2026_ARCHETYPES, ...existing]));
}
